name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test
        setup-command: ''
        command: javac LinearSearch.java && java LinearSearch
        input: 5 1 2 3 4 5 3
        expected-output: |-
          Enter the number of elements: Enter 5 elements:
          Enter the element to search: Element found at index: 2
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
